### ISSUE TITLE
Differentiate 2G vs. 3G?

### ISSUE THREAD

**Issue by fwenzel** [WICG/netinfo#10]
The current API draft differentiates between cellular and other connection types -- but not among "fast" and "slow" cellular connection types.

While the sheer existence of a 3G (and up) connection does not mean the data is actually transmitted at high speeds, there is a substantial difference between what you can do on 2G and what you can do on 3G and up.

I posit that the same kind of usecase that drives me (as a developer) to know if you're on cellular or not will only really be served if I can determine (with a certain level of confidence) what kind of connection you are on.

(This does not absolve me from the responsibility to treat bandwidth with respect -- fast data does not equal unmetered or free data -- but that's not the case for wifi either.)

**Comment by marcoscaceres** [comment]
@fwenzel, see the discussion here about bandwidth: http://w3c-webmob.github.io/netinfo-usecases/#why-not-expose-bandwidth

As there is no certainty about the speed of the connection based on the type, it would be harmful to expose this information. Right now, decisions about connection speed relate mostly to content type, mainly images and video. Those are handled by `<picture>` or by the `<video>` element + adaptive video streaming respectively. The main use cases this API is attempting to help with with is the "large download" and content sync use case. 

Hope that helps!

**Comment by fwenzel** [comment]
Thanks for the explanation, Marcos
