### ISSUE TITLE
Suggest 'unknown' connection type instead of 'other'

### ISSUE THREAD

**Issue by jkarlin** [WICG/netinfo#11]
There are times where it's difficult for the UA to determine what the connection type is. What should be the connection type in those cases?  Unknown is more accurate than other.

**Comment by marcoscaceres** [comment]
Agree, 'unknown'  makes sense there. Just to be clear, we probably just need to come up with a good definition for how it differs form "none" and "other". I.e., the connection is established, but the type can't be determined.

**Comment by marcoscaceres** [comment]
@jkarlin if you have a concrete situation where this comes up, that would be really helpful.

**Comment by jkarlin** [comment]
It's probably possible to get all of these types on all of the platforms that browsers run on, but there are several cases in Chromium (e.g., desktop) where bluetooth and cellular are not distinguished. We may fill them all out eventually but it will take time.

**Comment by marcoscaceres** [comment]
@jkarlin for your review: https://github.com/w3c/netinfo/pull/12

I've kept `other`, because it's slightly different: it means "connection type is known, but it's not in the list of enums". Hope that works for you.

**Comment by jkarlin** [comment]
Perfect, thank you.
