### ISSUE TITLE
W3C link in spec is broken

### ISSUE THREAD

**Issue by tagawa** [WICG/netinfo#20]
The "published version" link in https://w3c.github.io/netinfo/ points to http://www.w3.org/TR/netinfo/ which returns a 404. http://www.w3.org/TR/netinfo-api/ exists but is a shelved spec. Should the "published version" link be updated or just removed?

**Comment by igrigorik** [comment]
We need to update the w3.org version, and point the editor draft to this repo. 

@marcoscaceres who's the right person to ping on the W3C side?

**Comment by dontcallmedom** [comment]
@igrigorik I guess the main thing is to bring an update to the public-device-apis@w3.org mailing list to "unshelve" the spec and published an updated TR draft (with the updated link to the editors draft)

**Comment by tagawa** [comment]
Great, thank you.
