### ISSUE TITLE
Add WiMax as an underlying connection technology?

### ISSUE THREAD

**Issue by jkarlin** [WICG/netinfo#21]
Android supports wimax and it would be nice to provide a max download speed for it from the spec.

**Comment by marcoscaceres** [comment]
Sure, np. Do you have a value we can add to the JSON file?

**Comment by igrigorik** [comment]
@jkarlin do we have any stats on wimax usage in the wild? Also, for speed, is it a similar (Android) API to WiFi, where speed is returned from the network interface?

**Comment by jkarlin** [comment]
I don't have stats on wimax usage, I imagine it's quite small.  

According to http://en.wikipedia.org/wiki/WiMAX:

WiMax rel 1: 37Mbps down, 17 up
WiMax rel 1.5: 141 down, 138 up
WiMax rel 2: 365 down, 376 up

I don't see a way of getting release information from Android, so it will wind up being +infinity anyway.

**Comment by marcoscaceres** [comment]
I guess if the version is unknown, the max theoretical would then be 365 (i.e., the highest known value for the current generation)? But yeah, the question is if anyone would actually benefit from us adding this as WiMAX usage might indeed be statistically insignificant. Do we expect that to change? let me know how you want to proceed.

**Comment by igrigorik** [comment]
@marcoscaceres afaik, WiMax usage is small and going downhill. That said, I don't see any issues with adding it to the spec. If a particular platform doesn't support WiMax they don't incur any implementation cost.

**Comment by marcoscaceres** [comment]
@igrigorik ok, lets add it. I know next to nothing about it, so does it fall under the "cellular" group?
