### ISSUE TITLE
Incorrect 802.11ac maximum speed

### ISSUE THREAD

**Issue by eligrey** [WICG/netinfo#33]
Edit: [Moved to this PR](https://github.com/w3c/netinfo/pull/34).

**Comment by igrigorik** [comment]
The table is populated via: https://github.com/w3c/netinfo/blob/gh-pages/downlink.json. Up for making a pull request? :)

**Comment by eligrey** [comment]
Sure, [here's the PR](https://github.com/w3c/netinfo/pull/34).
