### ISSUE TITLE
Expose connection on WorkerNavigator?

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/netinfo#36]
The spec has `[Exposed=Window,Worker]` on the NetworkInformation interface, implying that the API is supposed to be available in workers. Yet it only defines a `connection` attribute on `Navigator`, not on `WorkerNavigator`. Is this an oversight? (For what it's worth chrome seems to implement it for `WorkerNavigator` as well).

**Comment by igrigorik** [comment]
Yes, an oversight!
