### ISSUE TITLE
w3c.github.io/netinfo link is dead, can we get it to redirect to wicg version?

### ISSUE THREAD

**Issue by igrigorik** [WICG/netinfo#39]
We have lots of links around the web pointing to w3c.github.io version..

**Comment by marcoscaceres** [comment]
Argh, thought it would redirect

**Comment by igrigorik** [comment]
The repo link does redirect (github.com/w3c/netinfo -> github.com/wicg/...). But the GitHub Pages redirect isn't there. 

I guess we'd have to recreate the w3c/netinfo repo and put a meta redirect in there?

**Comment by marcoscaceres** [comment]
> On 25 May 2016, at 1:47 AM, Ilya Grigorik notifications@github.com wrote:
> 
> The repo link does redirect (github.com/w3c/netinfo -> github.com/wicg/...). But the GitHub Pages redirect isn't there.
> 
> I guess we'd have to recreate the w3c/netinfo repo and put a meta redirect in there?

Yeah. Exactly. @dontcallmedom, can you recreate an empty "netinfo" repo for us, as above?

**Comment by dontcallmedom** [comment]
done; I gave write access to @marcoscaceres but let me know if more is needed

**Comment by marcoscaceres** [comment]
@dontcallmedom thanks! I've set up the redirect and added a README.

@igrigorik please check it's all good now and close.

**Comment by igrigorik** [comment]
Indeed, works great! Thanks guys.
