### ISSUE TITLE
downlinkMax type

### ISSUE THREAD

**Issue by stefhak** [WICG/netinfo#40]
Hi, downlinkMax has type "Megabit", but the table lists "+Infinity" as a valid value.
My real problem is that in testing the browser reports `Infinity` but JSON stringify translates that to null. I can easily work around, just wanted to raise this.

**Comment by marcoscaceres** [comment]
unfortunately, that's a limitation of JSON :( Not much we can do about this, but thanks for raising it.

**Comment by stefhak** [comment]
Just wondering why a type like "unsigned long" or "double" or something like that was not chosen.

**Comment by marcoscaceres** [comment]
@stefhak, IIRC, because we wanted it to return +Infinity for when there was a determined connection, but we didn't know (or wanted to obscure), the connection speed.
