### ISSUE TITLE
downlinkMax can be Infinity or undefined for connection.type='wifi'

### ISSUE THREAD

**Issue by leto** [WICG/netinfo#44]
Just started using this API and noticed that sometimes I see downlinkMax=Infinity or downlinkMax=undefined when the connection.type="wifi". The spec doesn't list Infinity/undefined as an option for "wifi", so I am wondering if this is a spec bug or implementation bug?
## Infinity
- Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG-SM-G530AZ Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 7.0; Nexus 5X Build/NRD90R) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36
## Undefined
- Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G900P Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

**Comment by jkarlin** [comment]
This is a Chrome-specific issue, so please file a bug on crbug.com in the future. I can tell you that Chrome doesn't know the wifi type as it doesn't have the required Android permission to get at that information so it returns +Infinity.

**Comment by igrigorik** [comment]
> This is a Chrome-specific issue, so please file a bug on crbug.com in the future.

+1. Closing this.
