### ISSUE TITLE
Formatting and linking issues with new respec version

### ISSUE THREAD

**Issue by igrigorik** [WICG/netinfo#49]
1. The table is not showing up and CSS styling for tables is missing?
   - Is there a cleanup step that's running on the table that's breaking our JS logic to populate the data?
   - When I create a new table, I don't see any CSS formatting for it.
1. Separately from above, it looks like new version of respec is throwing a lot of dfn warnings

![image](https://cloud.githubusercontent.com/assets/10652/25754449/127bc578-3174-11e7-86a2-37f3080d3ca2.png)

@marcoscaceres any tips for either of the above?

**Comment by igrigorik** [comment]
Managed to address some, but not all of the above in https://github.com/WICG/netinfo/pull/50. Tables are still not coming up.. and not sure how to correctly link the onchange dfn.

**Comment by marcoscaceres** [comment]
Apologies, seems I screwed something up and the markdown parser is eating the tables. Fixing...

**Comment by marcoscaceres** [comment]
Fix deployed... markdown is surprisingly hard 😅

**Comment by igrigorik** [comment]
Awesome, thank you!
