### ISSUE TITLE
Spec should specify the default values of RTT, throughput and effective connection type estimates

### ISSUE THREAD

**Issue by ghost** [WICG/netinfo#55]
NetInfo API exposes rtt, downlink and effectiveType attributes. It is possible that the user agent does not have a valid estimate of one of some of these attributes. For example, this may happen when the user agent has just started, or if the information is unavailable on certain platforms. The spec should specify the values for each of these 3 attributes that the user agent should return when a valid value is unavailable.

**Comment by igrigorik** [comment]
Resolved via #57.
