### ISSUE TITLE
Somewhat mangled IDL for NetworkInfomation

### ISSUE THREAD

**Issue by foolip** [WICG/netinfo#74]
The IDL block in https://wicg.github.io/netinfo/#-dfn-networkinformation-dfn-interface is:
```webidl
[Exposed=(Window,Worker)]
interface NetworkInformation : EventTarget {
  readonly attribute ConnectionType type;
  readonly attribute EffectiveConnectionType effectiveType;
  readonly attribute Megabit downlinkMax;
  readonly attribute Megabit downlink;
  readonly attribute Millisecond rtt;
  readonly attribute boolean saveData;
  attribute EventHandler onchange;
};typedef unrestricted double Megabit;typedef unsigned long long Millisecond;
```

Note the lack of newlines at the end. This doesn't match the source and is probably a ReSpec bug, but I don't know so am filing a bug here first.

**Comment by igrigorik** [comment]
Indeed. Perhaps a mistake in how we wired up something on this end.. 

@marcoscaceres any tips? :)

**Comment by marcoscaceres** [comment]
sorry I didn't see this earlier... it was fixed a while ago :)
