### ISSUE TITLE
compatibilité d'affichage mobile 

### ISSUE THREAD

**Issue by bacharacherif** [WICG/netinfo#90]
je Vien de faire le teste de mon blogspot.com sur google console 
sa m'affiches test pas tro compatible avec le mobile 
  merci si vous pouvais mes redirige

**Comment by yoavweiss** [comment]
Ceci n'est pas le bon forum pour votre demande d'aide. Vous pouvez essayer la [communauté d'aide de Google Search Console](https://support.google.com/webmasters/community?hl=fr) ou [stackoverflow.com](https://stackoverflow.com/). 
Bon courage! :)
